#!/usr/bin/env ruby

# frozen_string_literal: true

CONTENT_PLACEHOLDER = '<!-- content -->'

template = File.read('template.html')
content = File.read('privacy.md')

File.open('index.html', 'w') do |index|
  index.write(template.gsub(CONTENT_PLACEHOLDER, content))
end
